# Generated by Django 5.1.2 on 2024-10-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
